- docker-compose -f docker-compose-build.yaml build --parallel

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

- docker tag udagram-frontend:latest sasa94s/udagram-frontend:latest
- docker push sasa94s/udagram-frontend:latest

- docker tag udagram-api-feed:latest sasa94s/udagram-api-feed:latest
- docker push sasa94s/udagram-api-feed:latest

- docker tag udagram-api-user:latest sasa94s/udagram-api-user:latest
- docker push sasa94s/udagram-api-user:latest

- docker tag reverseproxy:latest sasa94s/reverseproxy:latest
- docker push sasa94s/reverseproxy:latest

