apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reverseproxy-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reverseproxy
    subresource: scale
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
