version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  udagram-api-users-service:
    build:
      context: ./udagram-api/users-service
    image: udagram-api-user
  udagram-api-feed-service:
    build:
      context: ./udagram-api/feed-service
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
